name: "Website: Build-and-Release"

concurrency:
  group: ${{ github.head_ref }}-charts-website-release

on:
  workflow_call:
  workflow_dispatch:
  #pull_request:
  #  paths:
  #    - "charts/**"
  #    - "/**"
  push:
    branches:
      - main
    paths:
      - "/**"
      - ".github/workflows/website.yaml"

# Use `bash --noprofile --norc -exo pipefail` by default for all `run` steps in this workflow:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.filter.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        with:
          list-files: json
          filters: |
            changed:
            - '**'


  release-website:
    permissions:
      pull-requests: write
    name: "${{ github.ref == 'refs/heads/main' && '(Production)' || '(Preview)' }}"
    runs-on:
      group: default
    needs: check_changes
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 1

      - name: Comment deploy start
        if: github.event_name != 'push' && needs.check_changes.outputs.changes_detected == 'true'
        continue-on-error: true
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-id: cloudflare-deploy
          message: |
            ### 🚧 Deploy Preview building...

            |  Name               | Link                                                                          |
            |---------------------|-------------------------------------------------------------------------------|
            |🔨 Latest commit     | ${{ github.sha }}                                                             |
            |🔍 Latest deploy log | https:/github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            ---

      - name: Setup Node
        if: needs.check_changes.outputs.changes_detected == 'true' && needs.check_changes.outputs.changes_detected == 'true'
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: ./.nvmrc

      - name: Fix Package-Lock
        if: needs.check_changes.outputs.changes_detected == 'true'
        run: cd website && npm i --package-lock-only

      - name: Setup astro Cache
        if: needs.check_changes.outputs.changes_detected == 'true'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          # Cache for build and optimized images.
          key: astro-${{ hashFiles('/package-lock.json') }}
          path: ./.astro
          restore-keys: astro-

      - name: Setup npm Cache
        if: needs.check_changes.outputs.changes_detected == 'true'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          # Cache for npm
          path: ~/.npm
          key: npm-${{ hashFiles('/package-lock.json') }}
          restore-keys: npm-

      - name: Setup node_modules Cache
        id: modulescache
        if: needs.check_changes.outputs.changes_detected == 'true'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          # Cache for npm and optimized images.
          path: ./node_modules
          key: modules-${{ hashFiles('/package-lock.json') }}

      - name: Install Packages
        if: steps.modulescache.outputs.cache-hit != 'true' && needs.check_changes.outputs.changes_detected == 'true'
        run: cd website && npm ci

      - name: Check
        if: needs.check_changes.outputs.changes_detected == 'true'
        run: cd website && npm run check

      - name: Build
        if: needs.check_changes.outputs.changes_detected == 'true'
        run: cd website && npm run build

      - name: Comment deploy start
        if: github.event_name != 'push' && needs.check_changes.outputs.changes_detected == 'true'
        continue-on-error: true
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-id: cloudflare-deploy
          message: |
            ### 🚧 Deploy Preview building...

            |  Name               | Link                                                                          |
            |---------------------|-------------------------------------------------------------------------------|
            |🔨 Latest commit     | ${{ github.sha }}                                                             |
            |🔍 Latest deploy log | https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            ---

      - name: Publish to Cloudflare Pages
        if: needs.check_changes.outputs.changes_detected == 'true'
        id: cloudflare
        continue-on-error: true
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # By default Cloudflare marks `main` as the "production" branch.
          # So when this workflow is pushed to refs/heads/main, we set the branch to `main`/"production".
          branch: ${{ github.ref == 'refs/heads/main' && 'main' || github.head_ref }}
          # The project name in Cloudflare
          projectName: trueforge-website
          directory: ./website
          wranglerVersion: "3"

      - name: Comment deploy url
        if: github.event_name != 'push' && needs.check_changes.outputs.changes_detected == 'true'
        continue-on-error: true
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-id: cloudflare-deploy
          message: |
            ### ✅ Deploy Preview ready!

            |  Name                | Link                                                                          |
            |----------------------|-------------------------------------------------------------------------------|
            |🔨 Latest commit      | ${{ github.sha }}                                                             |
            |🔍 Latest deploy log  | https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            |😎 Deploy Preview Url | [${{ steps.cloudflare.outputs.url }}](${{ steps.cloudflare.outputs.url }})    |
            |🌳 Environment        | ${{ steps.cloudflare.outputs.environment }}                                   |
            ---

      - name: Release-and-Website Completed
        if: needs.check_changes.outputs.changes_detected == 'true'
        run: echo "DONE"